export const ACTION_TYPE = {
	ADD_RESERVATION_ASYNC: "ADD_RESERVATION_ASYNC",
	ADD_RESERVATION: "ADD_RESERVATION",
	CLOSE_MODAL: "CLOSE_MODAL",
	LOAD_ROOM: "LOAD_ROOM",
	LOGOUT: "LOGOUT",
	OPEN_MODAL: "OPEN_MODAL",
	REMOVE_RESERVATION_ASYNC: "REMOVE_RESERVATION_ASYNC",
	REMOVE_RESERVATION: "REMOVE_RESERVATION",
	RESET_ROOM_DATA: "RESET_ROOM_DATA",
	SAVE_ROOM_ASYNC: "SAVE_ROOM_ASYNC",
	SET_ROOM_DATA: "SET_ROOM_DATA",
	SET_USER: "SET_USER",
};
